monolog:
  channels: ['od_klaviyo']

  handlers:
    klaviOverdLogHandler:
      type: rotating_file
      path: "%kernel.logs_dir%/[%kernel.environment%]klaviyo-integration.log"
      level: debug
      channels: [ "od_klaviyo" ]